/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import com.github.britooo.looca.api.core.Looca;
import com.github.britooo.looca.api.group.discos.Disco;
import com.github.britooo.looca.api.group.discos.DiscoGrupo;
import com.github.britooo.looca.api.group.memoria.Memoria;
import com.github.britooo.looca.api.group.processador.Processador;
import com.github.britooo.looca.api.util.Conversor;
import java.awt.Color;
import java.util.List;

/**
 *
 * @author eduardo
 */
public class CadastroPrimeiraVez extends javax.swing.JFrame {
    Looca looca = new Looca();
    Utilitarios util = new Utilitarios();

    /**
     * Creates new form CadastroPrimeiraVez
     */
    public CadastroPrimeiraVez() {
        initComponents();
        util.InserirIcone(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblMemoriaMassaTamanho = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lblProcessadorID = new javax.swing.JTextField();
        lblProcessadorFabricante = new javax.swing.JTextField();
        lblProcessadorNome = new javax.swing.JTextField();
        lblProcessadorCPUFisica = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lblProcessadorCPULogica = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        lblRAMTotal = new javax.swing.JTextField();
        lblMemoriaMassaNome = new javax.swing.JTextField();
        lblMemoriaMassaModelo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnPreenchimentoAutomatico = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1175, 679));
        setSize(new java.awt.Dimension(1200, 800));
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/imgCadastro.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 0, 510, 680);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Memória de massa:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(720, 410, 290, 20);

        lblMemoriaMassaTamanho.setBackground(new java.awt.Color(255, 255, 255));
        lblMemoriaMassaTamanho.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMemoriaMassaTamanho.setForeground(new java.awt.Color(183, 183, 183));
        lblMemoriaMassaTamanho.setText("Tamanho");
        lblMemoriaMassaTamanho.setToolTipText("");
        lblMemoriaMassaTamanho.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        lblMemoriaMassaTamanho.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lblMemoriaMassaTamanhoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lblMemoriaMassaTamanhoFocusLost(evt);
            }
        });
        lblMemoriaMassaTamanho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblMemoriaMassaTamanhoActionPerformed(evt);
            }
        });
        getContentPane().add(lblMemoriaMassaTamanho);
        lblMemoriaMassaTamanho.setBounds(720, 510, 290, 30);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Cadastro");
        jLabel6.setFocusable(false);
        jLabel6.setName(""); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(660, 60, 410, 50);

        lblProcessadorID.setBackground(new java.awt.Color(255, 255, 255));
        lblProcessadorID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblProcessadorID.setForeground(new java.awt.Color(183, 183, 183));
        lblProcessadorID.setText("ID Processador");
        lblProcessadorID.setToolTipText("");
        lblProcessadorID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        lblProcessadorID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lblProcessadorIDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lblProcessadorIDFocusLost(evt);
            }
        });
        lblProcessadorID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblProcessadorIDActionPerformed(evt);
            }
        });
        getContentPane().add(lblProcessadorID);
        lblProcessadorID.setBounds(720, 150, 290, 30);

        lblProcessadorFabricante.setBackground(new java.awt.Color(255, 255, 255));
        lblProcessadorFabricante.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblProcessadorFabricante.setForeground(new java.awt.Color(183, 183, 183));
        lblProcessadorFabricante.setText("Fabricante");
        lblProcessadorFabricante.setToolTipText("");
        lblProcessadorFabricante.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        lblProcessadorFabricante.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lblProcessadorFabricanteFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lblProcessadorFabricanteFocusLost(evt);
            }
        });
        lblProcessadorFabricante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblProcessadorFabricanteActionPerformed(evt);
            }
        });
        getContentPane().add(lblProcessadorFabricante);
        lblProcessadorFabricante.setBounds(720, 190, 290, 30);

        lblProcessadorNome.setBackground(new java.awt.Color(255, 255, 255));
        lblProcessadorNome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblProcessadorNome.setForeground(new java.awt.Color(183, 183, 183));
        lblProcessadorNome.setText("Nome Processador");
        lblProcessadorNome.setToolTipText("");
        lblProcessadorNome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        lblProcessadorNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lblProcessadorNomeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lblProcessadorNomeFocusLost(evt);
            }
        });
        lblProcessadorNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblProcessadorNomeActionPerformed(evt);
            }
        });
        getContentPane().add(lblProcessadorNome);
        lblProcessadorNome.setBounds(720, 230, 290, 30);

        lblProcessadorCPUFisica.setBackground(new java.awt.Color(255, 255, 255));
        lblProcessadorCPUFisica.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblProcessadorCPUFisica.setForeground(new java.awt.Color(183, 183, 183));
        lblProcessadorCPUFisica.setText("CPU Físicas");
        lblProcessadorCPUFisica.setToolTipText("");
        lblProcessadorCPUFisica.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        lblProcessadorCPUFisica.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lblProcessadorCPUFisicaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lblProcessadorCPUFisicaFocusLost(evt);
            }
        });
        lblProcessadorCPUFisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblProcessadorCPUFisicaActionPerformed(evt);
            }
        });
        getContentPane().add(lblProcessadorCPUFisica);
        lblProcessadorCPUFisica.setBounds(720, 270, 290, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Processador:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(720, 130, 290, 20);

        lblProcessadorCPULogica.setBackground(new java.awt.Color(255, 255, 255));
        lblProcessadorCPULogica.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblProcessadorCPULogica.setForeground(new java.awt.Color(183, 183, 183));
        lblProcessadorCPULogica.setText("CPU Lógicas");
        lblProcessadorCPULogica.setToolTipText("");
        lblProcessadorCPULogica.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        lblProcessadorCPULogica.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lblProcessadorCPULogicaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lblProcessadorCPULogicaFocusLost(evt);
            }
        });
        lblProcessadorCPULogica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblProcessadorCPULogicaActionPerformed(evt);
            }
        });
        getContentPane().add(lblProcessadorCPULogica);
        lblProcessadorCPULogica.setBounds(720, 310, 290, 30);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Memória RAM:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(720, 350, 290, 20);

        lblRAMTotal.setBackground(new java.awt.Color(255, 255, 255));
        lblRAMTotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblRAMTotal.setForeground(new java.awt.Color(183, 183, 183));
        lblRAMTotal.setText("Memória RAM");
        lblRAMTotal.setToolTipText("");
        lblRAMTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        lblRAMTotal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lblRAMTotalFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lblRAMTotalFocusLost(evt);
            }
        });
        lblRAMTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblRAMTotalActionPerformed(evt);
            }
        });
        getContentPane().add(lblRAMTotal);
        lblRAMTotal.setBounds(720, 370, 290, 30);

        lblMemoriaMassaNome.setBackground(new java.awt.Color(255, 255, 255));
        lblMemoriaMassaNome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMemoriaMassaNome.setForeground(new java.awt.Color(183, 183, 183));
        lblMemoriaMassaNome.setText("Nome");
        lblMemoriaMassaNome.setToolTipText("");
        lblMemoriaMassaNome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        lblMemoriaMassaNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lblMemoriaMassaNomeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lblMemoriaMassaNomeFocusLost(evt);
            }
        });
        lblMemoriaMassaNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblMemoriaMassaNomeActionPerformed(evt);
            }
        });
        getContentPane().add(lblMemoriaMassaNome);
        lblMemoriaMassaNome.setBounds(720, 430, 290, 30);

        lblMemoriaMassaModelo.setBackground(new java.awt.Color(255, 255, 255));
        lblMemoriaMassaModelo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMemoriaMassaModelo.setForeground(new java.awt.Color(183, 183, 183));
        lblMemoriaMassaModelo.setText("Modelo");
        lblMemoriaMassaModelo.setToolTipText("");
        lblMemoriaMassaModelo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        lblMemoriaMassaModelo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lblMemoriaMassaModeloFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lblMemoriaMassaModeloFocusLost(evt);
            }
        });
        lblMemoriaMassaModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblMemoriaMassaModeloActionPerformed(evt);
            }
        });
        getContentPane().add(lblMemoriaMassaModelo);
        lblMemoriaMassaModelo.setBounds(720, 470, 290, 30);

        jButton1.setBackground(new java.awt.Color(98, 165, 227));
        jButton1.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jButton1.setText("Cadastrar");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(760, 560, 160, 50);

        btnPreenchimentoAutomatico.setBackground(new java.awt.Color(98, 165, 227));
        btnPreenchimentoAutomatico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/refresh(1).png"))); // NOI18N
        btnPreenchimentoAutomatico.setToolTipText("Preenchimento automático");
        btnPreenchimentoAutomatico.setBorder(null);
        btnPreenchimentoAutomatico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreenchimentoAutomaticoActionPerformed(evt);
            }
        });
        getContentPane().add(btnPreenchimentoAutomatico);
        btnPreenchimentoAutomatico.setBounds(930, 560, 40, 50);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/boxCadastro.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(660, 0, 410, 680);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblMemoriaMassaTamanhoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblMemoriaMassaTamanhoFocusGained
        if(lblMemoriaMassaTamanho.getText().equals("Tamanho")){
            lblMemoriaMassaTamanho.setText("");
            lblMemoriaMassaTamanho.setForeground(new Color(000,000,000));
        }
    }//GEN-LAST:event_lblMemoriaMassaTamanhoFocusGained

    private void lblMemoriaMassaTamanhoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblMemoriaMassaTamanhoFocusLost
        if(lblMemoriaMassaTamanho.getText().equals("")){
            lblMemoriaMassaTamanho.setText("Tamanho");
            lblMemoriaMassaTamanho.setForeground(new Color(183,183,183));
        }
    }//GEN-LAST:event_lblMemoriaMassaTamanhoFocusLost

    private void lblMemoriaMassaTamanhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblMemoriaMassaTamanhoActionPerformed

    }//GEN-LAST:event_lblMemoriaMassaTamanhoActionPerformed

    private void lblProcessadorIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblProcessadorIDFocusGained
        if(lblProcessadorID.getText().equals("ID Processador")){
            lblProcessadorID.setText("");
            lblProcessadorID.setForeground(new Color(000,000,000));
        }
    }//GEN-LAST:event_lblProcessadorIDFocusGained

    private void lblProcessadorIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblProcessadorIDFocusLost
        if(lblProcessadorID.getText().equals("")){
            lblProcessadorID.setText("ID Processador");
            lblProcessadorID.setForeground(new Color(183,183,183));
        }
    }//GEN-LAST:event_lblProcessadorIDFocusLost

    private void lblProcessadorIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblProcessadorIDActionPerformed

    }//GEN-LAST:event_lblProcessadorIDActionPerformed

    private void lblProcessadorFabricanteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblProcessadorFabricanteFocusGained
        if(lblProcessadorFabricante.getText().equals("Fabricante")){
            lblProcessadorFabricante.setText("");
            lblProcessadorFabricante.setForeground(new Color(000,000,000));
        }
    }//GEN-LAST:event_lblProcessadorFabricanteFocusGained

    private void lblProcessadorFabricanteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblProcessadorFabricanteFocusLost
        if(lblProcessadorFabricante.getText().equals("")){
            lblProcessadorFabricante.setText("Fabricante");
            lblProcessadorFabricante.setForeground(new Color(183,183,183));
        }
    }//GEN-LAST:event_lblProcessadorFabricanteFocusLost

    private void lblProcessadorFabricanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblProcessadorFabricanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblProcessadorFabricanteActionPerformed

    private void lblProcessadorNomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblProcessadorNomeFocusGained
        if(lblProcessadorNome.getText().equals("Nome Processador")){
            lblProcessadorNome.setText("");
            lblProcessadorNome.setForeground(new Color(000,000,000));
        }
    }//GEN-LAST:event_lblProcessadorNomeFocusGained

    private void lblProcessadorNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblProcessadorNomeFocusLost
        if(lblProcessadorNome.getText().equals("")){
            lblProcessadorNome.setText("Nome Processador");
            lblProcessadorNome.setForeground(new Color(183,183,183));
        }
    }//GEN-LAST:event_lblProcessadorNomeFocusLost

    private void lblProcessadorNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblProcessadorNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblProcessadorNomeActionPerformed

    private void lblProcessadorCPUFisicaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblProcessadorCPUFisicaFocusGained
        if(lblProcessadorCPUFisica.getText().equals("CPU Físicas")){
            lblProcessadorCPUFisica.setText("");
            lblProcessadorCPUFisica.setForeground(new Color(000,000,000));
        }
    }//GEN-LAST:event_lblProcessadorCPUFisicaFocusGained

    private void lblProcessadorCPUFisicaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblProcessadorCPUFisicaFocusLost
        if(lblProcessadorCPUFisica.getText().equals("")){
            lblProcessadorCPUFisica.setText("CPU Físicas");
            lblProcessadorCPUFisica.setForeground(new Color(183,183,183));
        }
    }//GEN-LAST:event_lblProcessadorCPUFisicaFocusLost

    private void lblProcessadorCPUFisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblProcessadorCPUFisicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblProcessadorCPUFisicaActionPerformed

    private void lblProcessadorCPULogicaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblProcessadorCPULogicaFocusGained
        if(lblProcessadorCPULogica.getText().equals("CPU Lógicas")){
            lblProcessadorCPULogica.setText("");
            lblProcessadorCPULogica.setForeground(new Color(000,000,000));
        }
    }//GEN-LAST:event_lblProcessadorCPULogicaFocusGained

    private void lblProcessadorCPULogicaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblProcessadorCPULogicaFocusLost
        if(lblProcessadorCPULogica.getText().equals("")){
            lblProcessadorCPULogica.setText("CPU Lógicas");
            lblProcessadorCPULogica.setForeground(new Color(183,183,183));
        }
    }//GEN-LAST:event_lblProcessadorCPULogicaFocusLost

    private void lblProcessadorCPULogicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblProcessadorCPULogicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblProcessadorCPULogicaActionPerformed

    private void lblRAMTotalFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblRAMTotalFocusGained
        if(lblRAMTotal.getText().equals("Memória RAM")){
            lblRAMTotal.setText("");
            lblRAMTotal.setForeground(new Color(000,000,000));
        }
    }//GEN-LAST:event_lblRAMTotalFocusGained

    private void lblRAMTotalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblRAMTotalFocusLost
        if(lblRAMTotal.getText().equals("")){
            lblRAMTotal.setText("Memória RAM");
            lblRAMTotal.setForeground(new Color(183,183,183));
        }
    }//GEN-LAST:event_lblRAMTotalFocusLost

    private void lblRAMTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblRAMTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblRAMTotalActionPerformed

    private void lblMemoriaMassaNomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblMemoriaMassaNomeFocusGained
        if(lblMemoriaMassaNome.getText().equals("Nome")){
            lblMemoriaMassaNome.setText("");
            lblMemoriaMassaNome.setForeground(new Color(000,000,000));
        }
    }//GEN-LAST:event_lblMemoriaMassaNomeFocusGained

    private void lblMemoriaMassaNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblMemoriaMassaNomeFocusLost
        if(lblMemoriaMassaNome.getText().equals("")){
            lblMemoriaMassaNome.setText("Nome");
            lblMemoriaMassaNome.setForeground(new Color(183,183,183));
        }
    }//GEN-LAST:event_lblMemoriaMassaNomeFocusLost

    private void lblMemoriaMassaNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblMemoriaMassaNomeActionPerformed
        
    }//GEN-LAST:event_lblMemoriaMassaNomeActionPerformed

    private void lblMemoriaMassaModeloFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblMemoriaMassaModeloFocusGained
        if(lblMemoriaMassaModelo.getText().equals("Modelo")){
            lblMemoriaMassaModelo.setText("");
            lblMemoriaMassaModelo.setForeground(new Color(000,000,000));
        }
    }//GEN-LAST:event_lblMemoriaMassaModeloFocusGained

    private void lblMemoriaMassaModeloFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblMemoriaMassaModeloFocusLost
        if(lblMemoriaMassaModelo.getText().equals("")){
            lblMemoriaMassaModelo.setText("Modelo");
            lblMemoriaMassaModelo.setForeground(new Color(183,183,183));
        }
    }//GEN-LAST:event_lblMemoriaMassaModeloFocusLost

    private void lblMemoriaMassaModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblMemoriaMassaModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblMemoriaMassaModeloActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnPreenchimentoAutomaticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreenchimentoAutomaticoActionPerformed
        // TODO add your handling code here:
        Processador processador = looca.getProcessador();
        lblProcessadorID.setText(String.format("%s", processador.getId()));
        lblProcessadorFabricante.setText(String.format("%s", processador.getFabricante()));
        lblProcessadorNome.setText(String.format("%s", processador.getNome()));
        lblProcessadorCPUFisica.setText(String.format("%d", processador.getNumeroCpusFisicas()));
        lblProcessadorCPULogica.setText(String.format("%d", processador.getNumeroCpusLogicas()));
        
        Memoria memoria = looca.getMemoria();
        lblRAMTotal.setText(String.format("%s", Conversor.formatarBytes(memoria.getTotal())));
        
        DiscoGrupo grupoDeDiscos = looca.getGrupoDeDiscos();
        List<Disco> discos = grupoDeDiscos.getDiscos();
        for (int i = 0; i < discos.size(); i++){
            lblMemoriaMassaNome.setText(String.format("%s", discos.get(0).getNome()));
            lblMemoriaMassaModelo.setText(String.format("%s", discos.get(0).getModelo()));
            lblMemoriaMassaTamanho.setText(String.format("%s", Conversor.formatarBytes(discos.get(0).getTamanho())));
        }
    }//GEN-LAST:event_btnPreenchimentoAutomaticoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroPrimeiraVez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroPrimeiraVez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroPrimeiraVez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroPrimeiraVez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroPrimeiraVez().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPreenchimentoAutomatico;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField lblMemoriaMassaModelo;
    private javax.swing.JTextField lblMemoriaMassaNome;
    private javax.swing.JTextField lblMemoriaMassaTamanho;
    private javax.swing.JTextField lblProcessadorCPUFisica;
    private javax.swing.JTextField lblProcessadorCPULogica;
    private javax.swing.JTextField lblProcessadorFabricante;
    private javax.swing.JTextField lblProcessadorID;
    private javax.swing.JTextField lblProcessadorNome;
    private javax.swing.JTextField lblRAMTotal;
    // End of variables declaration//GEN-END:variables
}
