/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import com.github.britooo.looca.api.core.Looca;
import com.github.britooo.looca.api.group.discos.Disco;
import com.github.britooo.looca.api.group.discos.DiscoGrupo;
import com.github.britooo.looca.api.group.memoria.Memoria;
import com.github.britooo.looca.api.group.processador.Processador;
import com.github.britooo.looca.api.group.processos.Processo;
import com.github.britooo.looca.api.group.processos.ProcessoGrupo;
import com.github.britooo.looca.api.group.servicos.Servico;
import com.github.britooo.looca.api.group.servicos.ServicoGrupo;
import com.github.britooo.looca.api.util.Conversor;
import java.util.List;

/**
 *
 * @author Usuário
 */
public class TelaExibicaoDeDados extends javax.swing.JFrame {
    Looca looca = new Looca();
    /**
     * Creates new form TelaExibicaoDeDados
     */
    public TelaExibicaoDeDados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblInfoProcessadorFabricante = new javax.swing.JLabel();
        btnProcessador = new javax.swing.JButton();
        lblInfoProcessadorNome = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblInfoProcessadorCPUFisicas = new javax.swing.JLabel();
        lblInfoProcessadorCPULogica = new javax.swing.JLabel();
        lblInfoProcessadorEmUso = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblInfoRAMEmUso = new javax.swing.JLabel();
        lblInfoRAMDisponivel = new javax.swing.JLabel();
        lblInfoMemoriaMassaNome = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblInfoMemoriaMassaModelo = new javax.swing.JLabel();
        lblInfoMemoriaMassaTamanho = new javax.swing.JLabel();
        lblInfoRAMTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Processador:");

        lblInfoProcessadorFabricante.setText("Fabricante:");
        lblInfoProcessadorFabricante.setMaximumSize(new java.awt.Dimension(200, 500));

        btnProcessador.setText("Processador");
        btnProcessador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessadorActionPerformed(evt);
            }
        });

        lblInfoProcessadorNome.setText("Nome:");
        lblInfoProcessadorNome.setMaximumSize(new java.awt.Dimension(200, 500));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel2.setText("Dados do Computador");

        lblInfoProcessadorCPUFisicas.setText("Número de CPU Física:");
        lblInfoProcessadorCPUFisicas.setMaximumSize(new java.awt.Dimension(200, 500));

        lblInfoProcessadorCPULogica.setText("Número de CPU Lógica:");
        lblInfoProcessadorCPULogica.setMaximumSize(new java.awt.Dimension(200, 500));

        lblInfoProcessadorEmUso.setText("Em uso:");
        lblInfoProcessadorEmUso.setMaximumSize(new java.awt.Dimension(200, 500));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Memória RAM:");

        lblInfoRAMEmUso.setText("Em uso:");
        lblInfoRAMEmUso.setMaximumSize(new java.awt.Dimension(200, 500));

        lblInfoRAMDisponivel.setText("Disponível:");
        lblInfoRAMDisponivel.setMaximumSize(new java.awt.Dimension(200, 500));

        lblInfoMemoriaMassaNome.setText("Nome:");
        lblInfoMemoriaMassaNome.setMaximumSize(new java.awt.Dimension(200, 500));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Memória de Massa:");

        lblInfoMemoriaMassaModelo.setText("Modelo:");
        lblInfoMemoriaMassaModelo.setMaximumSize(new java.awt.Dimension(200, 500));

        lblInfoMemoriaMassaTamanho.setText("Tamanho:");
        lblInfoMemoriaMassaTamanho.setMaximumSize(new java.awt.Dimension(200, 500));

        lblInfoRAMTotal.setText("Total:");
        lblInfoRAMTotal.setMaximumSize(new java.awt.Dimension(200, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(330, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnProcessador)
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblInfoProcessadorNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblInfoProcessadorFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblInfoProcessadorCPUFisicas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblInfoProcessadorCPULogica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblInfoProcessadorEmUso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(lblInfoRAMEmUso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblInfoRAMDisponivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblInfoMemoriaMassaNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(lblInfoMemoriaMassaModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblInfoMemoriaMassaTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblInfoRAMTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel2))
                .addGap(334, 334, 334))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInfoProcessadorFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnProcessador))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(lblInfoProcessadorNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblInfoProcessadorCPUFisicas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInfoProcessadorCPULogica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInfoProcessadorEmUso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInfoRAMEmUso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInfoRAMDisponivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInfoRAMTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInfoMemoriaMassaNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInfoMemoriaMassaModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInfoMemoriaMassaTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(241, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProcessadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessadorActionPerformed
        // TODO add your handling code here:
        exibirProcessador();
    }//GEN-LAST:event_btnProcessadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaExibicaoDeDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaExibicaoDeDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaExibicaoDeDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaExibicaoDeDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaExibicaoDeDados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProcessador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblInfoMemoriaMassaModelo;
    private javax.swing.JLabel lblInfoMemoriaMassaNome;
    private javax.swing.JLabel lblInfoMemoriaMassaTamanho;
    private javax.swing.JLabel lblInfoProcessadorCPUFisicas;
    private javax.swing.JLabel lblInfoProcessadorCPULogica;
    private javax.swing.JLabel lblInfoProcessadorEmUso;
    private javax.swing.JLabel lblInfoProcessadorFabricante;
    private javax.swing.JLabel lblInfoProcessadorNome;
    private javax.swing.JLabel lblInfoRAMDisponivel;
    private javax.swing.JLabel lblInfoRAMEmUso;
    private javax.swing.JLabel lblInfoRAMTotal;
    // End of variables declaration//GEN-END:variables
    
    public void exibirProcessador(){
        Processador processador = looca.getProcessador();
        System.out.println(processador);
        lblInfoProcessadorFabricante.setText("Fabricante: " + processador.getFabricante());
        lblInfoProcessadorNome.setText("Nome: " + processador.getNome());
        lblInfoProcessadorCPUFisicas.setText("Número de CPU Física: " + processador.getNumeroCpusFisicas().toString());
        lblInfoProcessadorCPULogica.setText("Número de CPU Lógica: " + processador.getNumeroCpusLogicas().toString());
        lblInfoProcessadorEmUso.setText(String.format("Em uso: %.2f", processador.getUso()));
        
        Memoria memoria = looca.getMemoria();
        System.out.println(memoria);
        String memoriaEmUso = Conversor.formatarBytes(memoria.getEmUso());
        String memoriaTotal = Conversor.formatarBytes(memoria.getTotal());
        String memoriaDisponivel = Conversor.formatarBytes(memoria.getDisponivel());
        
        lblInfoRAMEmUso.setText(String.format("Em uso: %s", memoriaEmUso));
        lblInfoRAMDisponivel.setText(String.format("Disponível: %s", memoriaDisponivel));
        lblInfoRAMTotal.setText(String.format("Total: %s", memoriaTotal));
        
        
        DiscoGrupo grupoDeDiscos = looca.getGrupoDeDiscos();
        List<Disco> discos = grupoDeDiscos.getDiscos();
        for (Disco disco : discos) {
            System.out.println(disco);
            
            lblInfoMemoriaMassaNome.setText(String.format("Nome: %s", disco.getNome()));
            lblInfoMemoriaMassaModelo.setText(String.format("Modelo: %s", disco.getModelo()));
            lblInfoMemoriaMassaTamanho.setText(String.format("Tamanho: %s", Conversor.formatarBytes(disco.getTamanho())));
        }
        
        
        ServicoGrupo grupoDeServicos = new ServicoGrupo();
        List<Servico> servicos = grupoDeServicos.getServicosAtivos();
        for(int i = 0; i < servicos.size(); i++){
            
        }
        
        for(Servico servico : servicos){
            System.out.println(servico);
            
        
        }
        
        
        
                
                
                
        
    }
}
